before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: G9kqq8n9WzJhsRHbhRYGsgQo44iddcPSnohtVUe0E0thkqn0A/HRq7gz0efi2KB6xOIFQfrncUcTRdN/kh0UtM9m1kmbPkfndOmVY53hzr6IRydttH/mlehNhVslTbrnzpUbfxcyiFwVx/oBBaEi8XT4+ngii937Nb6DIgNZYNm+4eDKxyIFTOnm1fI36dxXtAwcUNdsmnk777nelfUvA0ghoVNWEXL8a7IEbttFeDDkVG2Yu8MJtyB3LQfzknAPONw2OafvOa6dOZaqcv3bQVyaSJX3EeFPh9okHrjORWdi/EUc3E80lPnHS+E7m/ZnhlsrpMFMyoBYbrsfZCaq7ZZ5s9FhZoQsiDVSe7gsTEjG1AIhG9OJ5juIVk6cbQSzGg7Om9/dWPPS5yv5aXV8OiSnGtws/RGf3zcWYiktejXzm549ZMVT4bwWnwRNnfessm+uxSdCPIOk9pIYKhqlGkojaoZ04AJB3iuL1gYpWEzXji4k5MH7DFj5hohohMWplByJ06TeBRoYQMjTT/nR+PdCSWb+1AU8yqMCGbHHwtfcg0FWzIWnccGV6c92eYJcmbJ1VUuTw7APqI3fH0pJwGAAzy7i8FgQq3HR9frQ3zQkjf9J1XlEvv0fPHJOOW7uFoTfGTN0ymjCeiHIe/3bdcmNKAmMhcc9qimWhXgcqXY= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
